<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class SdgController extends Controller
{
    private function getSdgs(): array
    {
        return [
            [
                'number'      => 1,
                'title'       => 'Tanpa Kemiskinan',
                'description' => 'Mengakhiri segala bentuk kemiskinan di semua tempat.',
                'targets'     => 7,
                'detail'      => 'SDG 1 bertujuan untuk mengakhiri kemiskinan dalam segala bentuknya di seluruh dunia. Ini mencakup kemiskinan ekstrem, akses terhadap sumber daya ekonomi, serta perlindungan sosial bagi kelompok rentan.',
                'points'      => [
                    '1.1 Pada tahun 2030, memberantas kemiskinan ekstrem bagi semua orang di mana pun, yang saat ini diukur dari penduduk yang hidup dengan pendapatan kurang dari $1,25 per hari.',
                    '1.2 Pada tahun 2030, mengurangi setidaknya setengah proporsi laki-laki, perempuan, dan anak-anak dari semua usia yang hidup dalam kemiskinan di semua dimensi, sesuai definisi nasional.',
                    '1.3 Menerapkan secara nasional sistem dan upaya perlindungan sosial yang tepat bagi semua, termasuk kelompok paling miskin, dan pada tahun 2030 mencapai cakupan substantif bagi kelompok miskin dan rentan.',
                    '1.4 Pada tahun 2030, menjamin bahwa semua laki-laki dan perempuan, khususnya masyarakat miskin dan rentan, memiliki hak yang sama terhadap sumber daya ekonomi, serta akses terhadap pelayanan dasar, kepemilikan dan kontrol atas tanah dan bentuk properti lainnya, warisan, sumber daya alam, teknologi baru, dan jasa keuangan yang tepat, termasuk keuangan mikro.',
                    '1.5 Pada tahun 2030, membangun ketahanan masyarakat miskin dan mereka yang berada dalam kondisi rentan, dan mengurangi kerentanan mereka terhadap kejadian ekstrem terkait iklim serta guncangan dan bencana ekonomi, sosial, dan lingkungan.',
                    '1.a Menjamin mobilisasi sumber daya yang signifikan dari berbagai sumber, termasuk melalui peningkatan kerja sama pembangunan, untuk menyediakan sarana yang memadai dan terjangkau bagi negara berkembang dalam melaksanakan program dan kebijakan mengakhiri kemiskinan di semua dimensi.',
                    '1.b Menciptakan kerangka kebijakan yang kuat di tingkat nasional, regional, dan internasional, berdasarkan strategi pembangunan yang berpihak pada kelompok miskin dan mempertimbangkan kepekaan gender, untuk mendukung investasi yang dipercepat dalam upaya pemberantasan kemiskinan.',
                ],
                'rce_action'  => 'RCE Jawa Timur mendukung program pemberdayaan ekonomi komunitas melalui pelatihan vokasi, pengembangan usaha mikro, dan pendampingan kelompok rentan di berbagai kabupaten/kota Jawa Timur.',
            ],
            [
                'number'      => 2,
                'title'       => 'Tanpa Kelaparan',
                'description' => 'Mengakhiri kelaparan, mencapai ketahanan pangan dan gizi yang baik, serta meningkatkan pertanian berkelanjutan.',
                'targets'     => 8,
                'detail'      => 'SDG 2 berfokus pada pencapaian ketahanan pangan, perbaikan gizi, dan peningkatan pertanian berkelanjutan. Tujuan ini mengakui keterkaitan antara pertanian, gizi, dan keberlanjutan lingkungan.',
                'points'      => [
                    '2.1 Pada tahun 2030, mengakhiri kelaparan dan menjamin akses bagi semua orang, khususnya masyarakat miskin dan mereka yang berada dalam kondisi rentan termasuk bayi, terhadap makanan yang aman, bergizi, dan cukup sepanjang tahun.',
                    '2.2 Pada tahun 2030, mengakhiri segala bentuk kekurangan gizi, termasuk mencapai target yang disepakati secara internasional untuk penanganan stunting dan wasting pada anak di bawah usia 5 tahun, dan memenuhi kebutuhan gizi remaja perempuan, ibu hamil dan menyusui, serta lansia.',
                    '2.3 Pada tahun 2030, menggandakan produktivitas pertanian dan pendapatan produsen pangan skala kecil, khususnya perempuan, masyarakat adat, petani keluarga, peternak, dan nelayan, termasuk melalui akses yang aman dan merata terhadap lahan, sumber daya produktif dan input, pengetahuan, layanan keuangan, pasar, dan peluang nilai tambah serta lapangan kerja non-pertanian.',
                    '2.4 Pada tahun 2030, menjamin sistem produksi pangan yang berkelanjutan dan menerapkan praktik pertanian tangguh yang meningkatkan produktivitas dan produksi, membantu menjaga ekosistem, memperkuat kapasitas adaptasi terhadap perubahan iklim, cuaca ekstrem, kekeringan, banjir, dan bencana lainnya, serta secara progresif meningkatkan kualitas tanah dan lahan.',
                    '2.5 Pada tahun 2020, menjaga keragaman genetik benih, tanaman budidaya, serta hewan ternak dan peliharaan dan spesies liar terkait, termasuk melalui bank benih dan tanaman yang dikelola dan didiversifikasi dengan baik di tingkat nasional, regional, dan internasional.',
                    '2.a Meningkatkan investasi, termasuk melalui peningkatan kerja sama internasional, dalam infrastruktur pedesaan, penelitian dan layanan penyuluhan pertanian, pengembangan teknologi, serta bank gen untuk tanaman dan ternak.',
                    '2.b Memperbaiki dan mencegah pembatasan perdagangan dan distorsi di pasar pertanian dunia, termasuk melalui penghapusan paralel semua bentuk subsidi ekspor pertanian dan semua tindakan ekspor dengan dampak setara.',
                    '2.c Mengadopsi langkah-langkah untuk menjamin berfungsinya pasar komoditas pangan dan turunannya secara baik dan memfasilitasi akses terhadap informasi pasar secara tepat waktu, termasuk cadangan pangan, untuk membatasi volatilitas harga pangan yang ekstrem.',
                ],
                'rce_action'  => 'RCE Jawa Timur mendukung pertanian organik, urban farming, dan program edukasi gizi masyarakat bekerja sama dengan dinas pertanian dan institusi riset pangan di Jawa Timur.',
            ],
            [
                'number'      => 3,
                'title'       => 'Kehidupan Sehat dan Sejahtera',
                'description' => 'Menjamin kehidupan yang sehat dan meningkatkan kesejahteraan seluruh penduduk semua usia.',
                'targets'     => 13,
                'detail'      => 'SDG 3 mencakup berbagai aspek kesehatan mulai dari kesehatan ibu dan anak, penanganan penyakit menular dan tidak menular, kesehatan mental, hingga akses layanan kesehatan universal.',
                'points'      => [
                    '3.1 Pada tahun 2030, mengurangi rasio kematian ibu hingga kurang dari 70 per 100.000 kelahiran hidup.',
                    '3.2 Pada tahun 2030, mengakhiri kematian bayi baru lahir dan balita yang dapat dicegah, dengan seluruh negara berusaha mengurangi kematian neonatal setidaknya 12 per 1.000 kelahiran hidup dan kematian balita setidaknya 25 per 1.000 kelahiran hidup.',
                    '3.3 Pada tahun 2030, mengakhiri epidemi AIDS, tuberkulosis, malaria, dan penyakit tropis yang terabaikan, serta memerangi hepatitis, penyakit bersumber air, dan penyakit menular lainnya.',
                    '3.4 Pada tahun 2030, mengurangi sepertiga kematian prematur akibat penyakit tidak menular melalui pencegahan dan pengobatan, serta meningkatkan kesehatan mental dan kesejahteraan.',
                    '3.5 Memperkuat pencegahan dan pengobatan penyalahgunaan zat, termasuk penyalahgunaan narkotika dan penggunaan alkohol yang berbahaya.',
                    '3.6 Pada tahun 2020, mengurangi setengah jumlah kematian dan cedera global akibat kecelakaan lalu lintas.',
                    '3.7 Pada tahun 2030, menjamin akses universal terhadap layanan kesehatan seksual dan reproduksi, termasuk keluarga berencana, informasi dan pendidikan, serta integrasi kesehatan reproduksi ke dalam strategi dan program nasional.',
                    '3.8 Mencapai cakupan kesehatan universal, termasuk perlindungan risiko keuangan, akses terhadap layanan kesehatan esensial yang berkualitas, serta akses terhadap obat-obatan dan vaksin esensial yang aman, efektif, berkualitas, dan terjangkau bagi semua orang.',
                    '3.9 Pada tahun 2030, secara substansial mengurangi jumlah kematian dan kesakitan akibat bahan kimia berbahaya serta polusi dan kontaminasi udara, air, dan tanah.',
                    '3.a Memperkuat pelaksanaan Kerangka Konvensi WHO tentang Pengendalian Tembakau di semua negara.',
                    '3.b Mendukung penelitian dan pengembangan vaksin dan obat-obatan untuk penyakit menular dan tidak menular yang terutama menyerang negara berkembang.',
                    '3.c Meningkatkan secara substansial pembiayaan kesehatan dan rekrutmen, pengembangan, pelatihan, dan retensi tenaga kesehatan di negara berkembang, khususnya negara kurang berkembang.',
                    '3.d Memperkuat kapasitas semua negara, khususnya negara berkembang, dalam hal peringatan dini, pengurangan risiko, dan pengelolaan risiko kesehatan nasional dan global.',
                ],
                'rce_action'  => 'RCE Jawa Timur mengintegrasikan pendidikan kesehatan lingkungan dalam kurikulum sekolah dan program komunitas, termasuk kampanye sanitasi dan perilaku hidup bersih sehat.',
            ],
            [
                'number'      => 4,
                'title'       => 'Pendidikan Berkualitas',
                'description' => 'Menjamin kualitas pendidikan yang inklusif dan merata serta meningkatkan kesempatan belajar sepanjang hayat untuk semua.',
                'targets'     => 10,
                'detail'      => 'SDG 4 adalah inti dari misi RCE Jawa Timur. Education for Sustainable Development (ESD) menjadi pendekatan utama untuk memastikan setiap orang mendapat akses pendidikan berkualitas yang relevan dengan tantangan abad ke-21.',
                'points'      => [
                    '4.1 Pada tahun 2030, menjamin bahwa semua anak perempuan dan laki-laki menyelesaikan pendidikan dasar dan menengah yang bebas biaya, setara, dan berkualitas, yang mengarah pada capaian pembelajaran yang relevan dan efektif.',
                    '4.2 Pada tahun 2030, menjamin bahwa semua anak perempuan dan laki-laki memiliki akses terhadap perkembangan dan pengasuhan anak usia dini serta pendidikan pra-sekolah dasar yang berkualitas, sehingga mereka siap untuk menempuh pendidikan dasar.',
                    '4.3 Pada tahun 2030, menjamin akses setara bagi semua perempuan dan laki-laki terhadap pendidikan teknis, kejuruan, dan tinggi yang terjangkau dan berkualitas, termasuk universitas.',
                    '4.4 Pada tahun 2030, meningkatkan secara substansial jumlah pemuda dan orang dewasa yang memiliki keterampilan yang relevan, termasuk keterampilan teknis dan kejuruan, untuk pekerjaan, lapangan kerja yang layak, dan kewirausahaan.',
                    '4.5 Pada tahun 2030, menghilangkan disparitas gender dalam pendidikan dan menjamin akses yang sama untuk semua tingkat pendidikan dan pelatihan kejuruan bagi masyarakat rentan, termasuk penyandang cacat, masyarakat adat, dan anak-anak dalam kondisi rentan.',
                    '4.6 Pada tahun 2030, menjamin bahwa semua remaja dan proporsi kelompok dewasa yang signifikan, baik laki-laki maupun perempuan, memiliki kemampuan literasi dan numerasi.',
                    '4.7 Pada tahun 2030, menjamin bahwa semua peserta didik memperoleh pengetahuan dan keterampilan yang diperlukan untuk mendukung pembangunan berkelanjutan, termasuk di antaranya melalui pendidikan untuk pembangunan berkelanjutan (ESD) dan gaya hidup berkelanjutan, hak asasi manusia, kesetaraan gender, promosi budaya perdamaian dan non-kekerasan, kewarganegaraan global, serta apresiasi terhadap keanekaragaman budaya.',
                    '4.a Membangun dan meningkatkan fasilitas pendidikan yang ramah anak, disabilitas, dan gender, serta menyediakan lingkungan belajar yang aman, tanpa kekerasan, inklusif, dan efektif bagi semua.',
                    '4.b Pada tahun 2020, memperluas secara global jumlah beasiswa yang tersedia bagi negara berkembang, khususnya negara kurang berkembang, negara berkembang kepulauan kecil, dan negara Afrika.',
                    '4.c Pada tahun 2030, meningkatkan secara substansial pasokan guru yang berkualitas, termasuk melalui kerja sama internasional untuk pelatihan guru di negara berkembang, terutama negara kurang berkembang dan negara berkembang kepulauan kecil.',
                ],
                'rce_action'  => 'ESD adalah fokus utama RCE Jawa Timur. Kami mengembangkan kurikulum berbasis keberlanjutan, melatih guru, dan menjalin kemitraan antara universitas, sekolah, dan komunitas.',
            ],
            [
                'number'      => 5,
                'title'       => 'Kesetaraan Gender',
                'description' => 'Mencapai kesetaraan gender dan memberdayakan kaum perempuan.',
                'targets'     => 9,
                'detail'      => 'SDG 5 bertujuan untuk mengakhiri diskriminasi terhadap perempuan dan anak perempuan, menghapus kekerasan berbasis gender, dan memastikan partisipasi penuh perempuan dalam kehidupan publik.',
                'points'      => [
                    '5.1 Mengakhiri segala bentuk diskriminasi terhadap semua perempuan dan anak perempuan di mana pun.',
                    '5.2 Menghapuskan segala bentuk kekerasan terhadap semua perempuan dan anak perempuan di ruang publik dan privat, termasuk perdagangan orang dan eksploitasi seksual dan berbagai jenis eksploitasi lainnya.',
                    '5.3 Menghapuskan semua praktik berbahaya, seperti perkawinan anak, perkawinan dini dan paksa, serta sunat perempuan.',
                    '5.4 Menghargai dan menghormati pelayanan pengasuhan dan pekerjaan rumah tangga yang tidak dibayar melalui penyediaan layanan publik, infrastruktur dan kebijakan perlindungan sosial, serta mendorong tanggung jawab bersama dalam rumah tangga dan keluarga.',
                    '5.5 Menjamin partisipasi penuh dan efektif, serta kesempatan yang sama bagi perempuan untuk memimpin di semua tingkat pengambilan keputusan dalam kehidupan politik, ekonomi, dan masyarakat.',
                    '5.6 Menjamin akses universal terhadap kesehatan seksual dan reproduksi serta hak-hak reproduksi sebagaimana disepakati dalam Programme of Action of the International Conference on Population and Development.',
                    '5.a Melakukan reformasi untuk memberikan hak yang sama kepada perempuan terhadap sumber daya ekonomi, serta akses terhadap kepemilikan dan kontrol atas tanah dan bentuk properti lainnya, jasa keuangan, warisan, dan sumber daya alam.',
                    '5.b Meningkatkan penggunaan teknologi yang memampukan, khususnya teknologi informasi dan komunikasi, untuk meningkatkan pemberdayaan perempuan.',
                    '5.c Mengadopsi dan memperkuat kebijakan yang baik dan perundang-undangan yang berlaku untuk peningkatan kesetaraan gender dan pemberdayaan kaum perempuan di semua tingkatan.',
                ],
                'rce_action'  => 'RCE Jawa Timur mendorong keterwakilan perempuan dalam program riset, kepemimpinan komunitas, dan pengambilan keputusan di bidang lingkungan dan pembangunan.',
            ],
            [
                'number'      => 6,
                'title'       => 'Air Bersih dan Sanitasi Layak',
                'description' => 'Menjamin ketersediaan serta pengelolaan air bersih dan sanitasi yang berkelanjutan untuk semua.',
                'targets'     => 8,
                'detail'      => 'SDG 6 mencakup akses air minum yang aman, sanitasi yang layak, kebersihan, kualitas air, efisiensi penggunaan air, pengelolaan ekosistem terkait air, serta kerjasama internasional dalam tata kelola air.',
                'points'      => [
                    '6.1 Pada tahun 2030, mencapai akses universal dan merata terhadap air minum yang aman dan terjangkau bagi semua.',
                    '6.2 Pada tahun 2030, mencapai akses terhadap sanitasi dan kebersihan yang memadai dan merata bagi semua, dan mengakhiri buang air besar sembarangan, dengan memberikan perhatian khusus pada kebutuhan perempuan dan anak perempuan serta mereka yang berada dalam situasi rentan.',
                    '6.3 Pada tahun 2030, meningkatkan kualitas air dengan mengurangi polusi, menghilangkan pembuangan limbah, dan meminimalkan pelepasan bahan kimia dan material berbahaya, mengurangi separuh proporsi air limbah yang tidak diolah, serta meningkatkan secara substansial daur ulang dan penggunaan kembali yang aman secara global.',
                    '6.4 Pada tahun 2030, meningkatkan secara substansial efisiensi penggunaan air di semua sektor, dan menjamin pengambilan dan pasokan air tawar yang berkelanjutan untuk mengatasi kelangkaan air, dan secara substansial mengurangi jumlah orang yang menderita akibat kelangkaan air.',
                    '6.5 Pada tahun 2030, menerapkan pengelolaan sumber daya air terpadu di semua tingkatan, termasuk melalui kerja sama lintas batas yang tepat.',
                    '6.6 Pada tahun 2020, melindungi dan merestorasi ekosistem terkait air, termasuk pegunungan, hutan, lahan basah, sungai, air tanah, dan danau.',
                    '6.a Pada tahun 2030, memperluas kerja sama dan dukungan internasional dalam hal pembangunan kapasitas kepada negara berkembang untuk kegiatan dan program terkait air dan sanitasi.',
                    '6.b Mendukung dan memperkuat partisipasi masyarakat lokal dalam upaya peningkatan pengelolaan air dan sanitasi.',
                ],
                'rce_action'  => 'RCE Jawa Timur aktif dalam program konservasi DAS Brantas, edukasi pengelolaan air komunitas, dan advokasi sanitasi layak di kawasan pesisir dan pedesaan.',
            ],
            [
                'number'      => 7,
                'title'       => 'Energi Bersih dan Terjangkau',
                'description' => 'Menjamin akses energi yang terjangkau, andal, berkelanjutan, dan modern untuk semua.',
                'targets'     => 5,
                'detail'      => 'SDG 7 berfokus pada tiga aspek utama: akses universal terhadap layanan energi, peningkatan pangsa energi terbarukan, dan peningkatan efisiensi energi secara global.',
                'points'      => [
                    '7.1 Pada tahun 2030, menjamin akses universal terhadap layanan energi modern yang terjangkau.',
                    '7.2 Pada tahun 2030, meningkatkan secara substansial pangsa energi terbarukan dalam bauran energi global.',
                    '7.3 Pada tahun 2030, menggandakan laju peningkatan efisiensi energi global.',
                    '7.a Pada tahun 2030, meningkatkan kerja sama internasional untuk memfasilitasi akses terhadap penelitian dan teknologi energi bersih, termasuk energi terbarukan, efisiensi energi, serta teknologi bahan bakar fosil yang lebih maju dan bersih.',
                    '7.b Pada tahun 2030, memperluas infrastruktur dan meningkatkan teknologi untuk penyediaan layanan energi modern dan berkelanjutan bagi semua di negara berkembang, khususnya negara kurang berkembang dan negara berkembang kepulauan kecil.',
                ],
                'rce_action'  => 'RCE Jawa Timur menjalankan proyek instalasi panel surya komunal di desa terpencil Madura dan Tapal Kuda, serta edukasi efisiensi energi di sekolah dan institusi.',
            ],
            [
                'number'      => 8,
                'title'       => 'Pekerjaan Layak dan Pertumbuhan Ekonomi',
                'description' => 'Meningkatkan pertumbuhan ekonomi yang inklusif dan berkelanjutan, tenaga kerja penuh dan produktif, serta pekerjaan yang layak untuk semua.',
                'targets'     => 12,
                'detail'      => 'SDG 8 menghubungkan pertumbuhan ekonomi dengan pekerjaan yang layak, produktivitas tenaga kerja, dan pengurangan pengangguran, sambil memastikan pertumbuhan tidak merusak lingkungan.',
                'points'      => [
                    '8.1 Mempertahankan pertumbuhan ekonomi per kapita sesuai dengan kondisi nasional, dan khususnya pertumbuhan produk domestik bruto minimal 7 persen per tahun di negara kurang berkembang.',
                    '8.2 Mencapai tingkat produktivitas ekonomi yang lebih tinggi melalui diversifikasi, peningkatan teknologi, dan inovasi, termasuk melalui fokus pada sektor bernilai tambah tinggi dan sektor padat karya.',
                    '8.3 Mendorong kebijakan pembangunan yang mendukung kegiatan produktif, penciptaan lapangan kerja yang layak, kewirausahaan, kreativitas, dan inovasi, serta mendorong formalisasi dan pertumbuhan usaha mikro, kecil, dan menengah.',
                    '8.4 Meningkatkan secara progresif efisiensi sumber daya global dalam konsumsi dan produksi, serta berusaha memisahkan pertumbuhan ekonomi dari degradasi lingkungan.',
                    '8.5 Pada tahun 2030, mencapai pekerjaan penuh dan produktif serta pekerjaan yang layak bagi semua perempuan dan laki-laki, termasuk bagi pemuda dan penyandang disabilitas, serta upah yang sama untuk pekerjaan yang sama nilainya.',
                    '8.6 Pada tahun 2020, secara substansial mengurangi proporsi pemuda yang tidak bekerja, tidak menempuh pendidikan, atau pelatihan.',
                    '8.7 Mengambil tindakan segera dan efektif untuk mengakhiri kerja paksa, mengakhiri perbudakan modern dan perdagangan orang, serta mengamankan larangan dan penghapusan bentuk-bentuk terburuk pekerja anak.',
                    '8.8 Melindungi hak-hak buruh dan mendorong lingkungan kerja yang aman dan terjamin bagi semua pekerja, termasuk pekerja migran, khususnya pekerja migran perempuan.',
                    '8.9 Pada tahun 2030, merancang dan melaksanakan kebijakan untuk mempromosikan pariwisata berkelanjutan yang menciptakan lapangan kerja dan mempromosikan budaya dan produk lokal.',
                    '8.10 Memperkuat kapasitas lembaga keuangan domestik untuk mendorong dan memperluas akses terhadap perbankan, asuransi, dan jasa keuangan bagi semua.',
                    '8.a Meningkatkan bantuan untuk perdagangan bagi negara berkembang, khususnya negara kurang berkembang.',
                    '8.b Pada tahun 2020, mengembangkan dan mengoperasionalkan strategi global untuk ketenagakerjaan pemuda dan melaksanakan Pakta Ketenagakerjaan Global ILO.',
                ],
                'rce_action'  => 'RCE Jawa Timur mendukung pengembangan green economy melalui pelatihan keterampilan hijau, kewirausahaan sosial, dan kemitraan dengan sektor swasta yang bertanggung jawab.',
            ],
            [
                'number'      => 9,
                'title'       => 'Industri, Inovasi dan Infrastruktur',
                'description' => 'Membangun infrastruktur yang tangguh, meningkatkan industri inklusif dan berkelanjutan, serta mendorong inovasi.',
                'targets'     => 8,
                'detail'      => 'SDG 9 menekankan pentingnya infrastruktur berkualitas, industrialisasi yang inklusif dan berkelanjutan, serta investasi dalam riset dan inovasi sebagai fondasi pembangunan.',
                'points'      => [
                    '9.1 Mengembangkan infrastruktur yang berkualitas, andal, berkelanjutan, dan tangguh, termasuk infrastruktur regional dan lintas batas, untuk mendukung pembangunan ekonomi dan kesejahteraan manusia.',
                    '9.2 Mendorong industrialisasi yang inklusif dan berkelanjutan, dan pada tahun 2030, meningkatkan secara signifikan pangsa industri dalam lapangan kerja dan produk domestik bruto.',
                    '9.3 Meningkatkan akses usaha kecil dan menengah di negara berkembang terhadap jasa keuangan, termasuk kredit yang terjangkau, dan integrasinya ke dalam rantai nilai dan pasar.',
                    '9.4 Pada tahun 2030, meningkatkan infrastruktur dan retrofit industri agar dapat berkelanjutan, dengan peningkatan efisiensi penggunaan sumber daya dan adopsi teknologi serta proses industri yang bersih dan ramah lingkungan.',
                    '9.5 Meningkatkan penelitian ilmiah, meningkatkan kapabilitas teknologi sektor industri di semua negara, mendorong inovasi, dan meningkatkan jumlah pekerja riset dan pengembangan serta pengeluaran untuk riset dan pengembangan publik dan swasta.',
                    '9.a Memfasilitasi pengembangan infrastruktur yang berkelanjutan dan tangguh di negara berkembang melalui peningkatan dukungan keuangan, teknologi, dan teknis kepada negara-negara Afrika, negara kurang berkembang, dan negara berkembang terkurung daratan.',
                    '9.b Mendukung pengembangan teknologi, riset dan inovasi domestik di negara berkembang, termasuk dengan memastikan lingkungan kebijakan yang kondusif untuk diversifikasi industri dan penambahan nilai komoditas.',
                    '9.c Secara signifikan meningkatkan akses terhadap teknologi informasi dan komunikasi serta berupaya menyediakan akses universal dan terjangkau ke internet di negara kurang berkembang pada tahun 2020.',
                ],
                'rce_action'  => 'RCE Jawa Timur bekerja sama dengan ITS dan universitas teknik di Jawa Timur untuk mengembangkan teknologi tepat guna yang berkelanjutan bagi komunitas lokal.',
            ],
            [
                'number'      => 10,
                'title'       => 'Berkurangnya Kesenjangan',
                'description' => 'Mengurangi kesenjangan di dalam dan antar negara.',
                'targets'     => 10,
                'detail'      => 'SDG 10 bertujuan untuk mengurangi ketimpangan pendapatan, mempromosikan inklusi sosial, ekonomi, dan politik bagi semua, serta memastikan kesempatan yang setara.',
                'points'      => [
                    '10.1 Pada tahun 2030, secara progresif mencapai dan mempertahankan pertumbuhan pendapatan dari 40% populasi terbawah pada tingkat yang lebih tinggi dari rata-rata nasional.',
                    '10.2 Pada tahun 2030, memberdayakan dan mendorong inklusi sosial, ekonomi, dan politik bagi semua, terlepas dari usia, jenis kelamin, disabilitas, ras, etnis, asal, agama, atau status ekonomi atau lainnya.',
                    '10.3 Menjamin kesempatan yang sama dan mengurangi kesenjangan hasil, termasuk dengan menghapus hukum, kebijakan, dan praktik yang diskriminatif.',
                    '10.4 Mengadopsi kebijakan, khususnya kebijakan fiskal, upah, dan perlindungan sosial, serta secara progresif mencapai kesetaraan yang lebih besar.',
                    '10.5 Meningkatkan regulasi dan pemantauan pasar dan lembaga keuangan global, serta memperkuat penerapan peraturan tersebut.',
                    '10.6 Memastikan keterwakilan dan suara yang lebih besar bagi negara berkembang dalam pengambilan keputusan di lembaga ekonomi dan keuangan internasional global.',
                    '10.7 Memfasilitasi migrasi dan mobilitas manusia yang tertib, aman, teratur, dan bertanggung jawab, termasuk melalui penerapan kebijakan migrasi yang terencana dan dikelola dengan baik.',
                    '10.a Menerapkan prinsip perlakuan khusus dan berbeda untuk negara berkembang, khususnya negara kurang berkembang, sesuai dengan perjanjian Organisasi Perdagangan Dunia.',
                    '10.b Mendorong bantuan pembangunan resmi dan arus keuangan, termasuk investasi asing langsung, ke negara-negara yang paling membutuhkan.',
                    '10.c Pada tahun 2030, mengurangi hingga kurang dari 3 persen biaya transaksi remitansi migran.',
                ],
                'rce_action'  => 'RCE Jawa Timur mendorong akses pendidikan berkualitas bagi kelompok marginal, termasuk komunitas adat, penyandang disabilitas, dan masyarakat pedesaan terpencil.',
            ],
            [
                'number'      => 11,
                'title'       => 'Kota dan Komunitas Berkelanjutan',
                'description' => 'Menjadikan kota dan permukiman inklusif, aman, tangguh, dan berkelanjutan.',
                'targets'     => 10,
                'detail'      => 'SDG 11 berfokus pada pembangunan perkotaan yang inklusif dan berkelanjutan, termasuk perumahan yang layak, transportasi publik, ruang hijau, serta pengurangan risiko bencana.',
                'points'      => [
                    '11.1 Pada tahun 2030, menjamin akses bagi semua terhadap perumahan yang layak, aman, dan terjangkau, serta layanan dasar, dan menata kawasan kumuh.',
                    '11.2 Pada tahun 2030, menyediakan akses terhadap sistem transportasi yang aman, terjangkau, mudah diakses, dan berkelanjutan untuk semua, meningkatkan keselamatan lalu lintas, terutama dengan memperluas angkutan umum.',
                    '11.3 Pada tahun 2030, meningkatkan urbanisasi yang inklusif dan berkelanjutan serta kapasitas perencanaan dan pengelolaan permukiman manusia yang partisipatif, terpadu, dan berkelanjutan di semua negara.',
                    '11.4 Memperkuat upaya untuk melindungi dan menjaga warisan budaya dan alam dunia.',
                    '11.5 Pada tahun 2030, secara signifikan mengurangi jumlah kematian dan jumlah orang terdampak bencana, serta mengurangi kerugian ekonomi akibat bencana.',
                    '11.6 Pada tahun 2030, mengurangi dampak lingkungan perkotaan per kapita yang merugikan, termasuk dengan memberikan perhatian khusus pada kualitas udara dan pengelolaan limbah kota.',
                    '11.7 Pada tahun 2030, menyediakan akses universal terhadap ruang publik yang aman, inklusif, dan mudah dijangkau, terutama untuk perempuan dan anak, lansia, dan penyandang disabilitas.',
                    '11.a Mendukung keterkaitan positif ekonomi, sosial, dan lingkungan antara daerah perkotaan, pinggiran kota, dan perdesaan dengan memperkuat perencanaan pembangunan nasional dan daerah.',
                    '11.b Pada tahun 2020, meningkatkan jumlah kota dan permukiman yang mengadopsi dan mengimplementasikan kebijakan dan rencana terpadu tentang inklusi, efisiensi sumber daya, mitigasi dan adaptasi perubahan iklim, serta ketahanan bencana.',
                    '11.c Mendukung negara-negara kurang berkembang dalam membangun bangunan yang berkelanjutan dan tangguh dengan memanfaatkan bahan-bahan lokal.',
                ],
                'rce_action'  => 'RCE Jawa Timur aktif dalam program kota berkelanjutan di Surabaya, Malang, dan Banyuwangi, mencakup tata ruang hijau, transportasi publik, dan mitigasi bencana perkotaan.',
            ],
            [
                'number'      => 12,
                'title'       => 'Konsumsi dan Produksi yang Bertanggung Jawab',
                'description' => 'Menjamin pola produksi dan konsumsi yang berkelanjutan.',
                'targets'     => 11,
                'detail'      => 'SDG 12 mendorong efisiensi penggunaan sumber daya alam, pengurangan limbah, dan pergeseran menuju pola konsumsi dan produksi yang lebih berkelanjutan di semua tingkatan.',
                'points'      => [
                    '12.1 Melaksanakan Kerangka Program 10 Tahun tentang Konsumsi dan Produksi Berkelanjutan, dengan semua negara mengambil tindakan, dipimpin negara maju.',
                    '12.2 Pada tahun 2030, mencapai pengelolaan berkelanjutan dan efisiensi penggunaan sumber daya alam.',
                    '12.3 Pada tahun 2030, mengurangi separuh limbah pangan per kapita global di tingkat eceran dan konsumen, serta mengurangi kehilangan pangan di sepanjang rantai produksi dan pasokan.',
                    '12.4 Pada tahun 2020, mencapai pengelolaan bahan kimia dan semua jenis limbah yang ramah lingkungan di sepanjang siklus hidupnya, serta secara signifikan mengurangi pelepasannya ke udara, air, dan tanah.',
                    '12.5 Pada tahun 2030, secara substansial mengurangi produksi limbah melalui pencegahan, pengurangan, daur ulang, dan penggunaan kembali.',
                    '12.6 Mendorong perusahaan, terutama perusahaan besar dan transnasional, untuk mengadopsi praktik-praktik berkelanjutan dan mengintegrasikan informasi keberlanjutan dalam siklus pelaporan mereka.',
                    '12.7 Mendorong praktik pengadaan publik yang berkelanjutan, sesuai dengan kebijakan dan prioritas nasional.',
                    '12.8 Pada tahun 2030, memastikan bahwa masyarakat di mana pun memiliki informasi yang relevan dan kesadaran tentang pembangunan berkelanjutan dan gaya hidup yang harmonis dengan alam.',
                    '12.a Mendukung negara berkembang untuk memperkuat kapasitas ilmu pengetahuan dan teknologi mereka menuju pola konsumsi dan produksi yang lebih berkelanjutan.',
                    '12.b Mengembangkan dan menerapkan alat pemantauan dampak pembangunan berkelanjutan untuk pariwisata berkelanjutan.',
                    '12.c Merasionalisasi subsidi bahan bakar fosil yang tidak efisien dan mendistorsi pasar dengan menghilangkan distorsi pasar.',
                ],
                'rce_action'  => 'RCE Jawa Timur menjalankan program bank sampah, daur ulang komunitas, dan edukasi konsumsi berkelanjutan di sekolah dan masyarakat di berbagai wilayah Jawa Timur.',
            ],
            [
                'number'      => 13,
                'title'       => 'Penanganan Perubahan Iklim',
                'description' => 'Mengambil tindakan cepat untuk mengatasi perubahan iklim dan dampaknya.',
                'targets'     => 5,
                'detail'      => 'SDG 13 menyerukan tindakan segera untuk memerangi perubahan iklim dan dampaknya, termasuk memperkuat ketahanan dan kemampuan adaptasi terhadap bahaya iklim.',
                'points'      => [
                    '13.1 Memperkuat ketahanan dan kemampuan adaptasi terhadap bahaya iklim dan bencana alam di semua negara.',
                    '13.2 Mengintegrasikan tindakan perubahan iklim ke dalam kebijakan, strategi, dan perencanaan nasional.',
                    '13.3 Meningkatkan pendidikan, penguatan kesadaran, serta kapasitas manusia dan institusi terkait mitigasi, adaptasi, pengurangan dampak, dan peringatan dini perubahan iklim.',
                    '13.a Melaksanakan komitmen negara-negara maju dalam UNFCCC untuk tujuan mobilisasi bersama $100 miliar per tahun mulai tahun 2020 dari berbagai sumber dalam rangka mengatasi kebutuhan negara berkembang.',
                    '13.b Mendorong mekanisme peningkatan kapasitas perencanaan dan pengelolaan yang efektif terkait perubahan iklim di negara kurang berkembang dan negara berkembang kepulauan kecil.',
                ],
                'rce_action'  => 'RCE Jawa Timur mengembangkan kurikulum perubahan iklim untuk pendidikan formal dan non-formal, serta mendampingi komunitas pesisir dalam adaptasi terhadap kenaikan permukaan laut.',
            ],
            [
                'number'      => 14,
                'title'       => 'Ekosistem Lautan',
                'description' => 'Melestarikan dan memanfaatkan secara berkelanjutan sumber daya kelautan dan samudra untuk pembangunan berkelanjutan.',
                'targets'     => 10,
                'detail'      => 'SDG 14 berfokus pada pencegahan polusi laut, perlindungan ekosistem laut dan pesisir, pengaturan penangkapan ikan yang berkelanjutan, dan konservasi kawasan laut.',
                'points'      => [
                    '14.1 Pada tahun 2025, mencegah dan secara signifikan mengurangi semua jenis polusi laut, khususnya dari kegiatan berbasis darat, termasuk sampah laut dan polusi nutrisi.',
                    '14.2 Pada tahun 2020, mengelola dan melindungi ekosistem laut dan pesisir secara berkelanjutan untuk menghindari dampak buruk yang signifikan, termasuk dengan memperkuat ketahanannya.',
                    '14.3 Meminimalkan dan mengatasi dampak pengasaman laut, termasuk melalui peningkatan kerja sama ilmiah di semua tingkatan.',
                    '14.4 Pada tahun 2020, secara efektif mengatur pemanenan ikan dan mengakhiri penangkapan ikan berlebihan, penangkapan ikan ilegal, dan praktik penangkapan ikan yang merusak.',
                    '14.5 Pada tahun 2020, melestarikan setidaknya 10 persen dari kawasan pesisir dan laut, konsisten dengan hukum nasional dan internasional.',
                    '14.6 Pada tahun 2020, melarang bentuk-bentuk subsidi perikanan tertentu yang berkontribusi pada kapasitas berlebih dan penangkapan ikan berlebihan, serta menghilangkan subsidi yang berkontribusi pada penangkapan ikan ilegal.',
                    '14.7 Pada tahun 2030, meningkatkan manfaat ekonomi bagi negara berkembang kepulauan kecil dan negara kurang berkembang dari penggunaan sumber daya laut secara berkelanjutan.',
                    '14.a Meningkatkan pengetahuan ilmiah, mengembangkan kapasitas penelitian, dan mentransfer teknologi kelautan.',
                    '14.b Memberikan akses nelayan skala kecil dan artisanal terhadap sumber daya laut dan pasar.',
                    '14.c Meningkatkan konservasi dan pemanfaatan berkelanjutan lautan dan sumber dayanya dengan menerapkan hukum internasional sebagaimana tercermin dalam UNCLOS.',
                ],
                'rce_action'  => 'RCE Jawa Timur menjalankan program pemulihan mangrove di pesisir Gresik-Sidoarjo dan edukasi konservasi terumbu karang bersama komunitas nelayan Madura.',
            ],
            [
                'number'      => 15,
                'title'       => 'Ekosistem Daratan',
                'description' => 'Melindungi, merestorasi, dan meningkatkan pemanfaatan berkelanjutan ekosistem daratan.',
                'targets'     => 12,
                'detail'      => 'SDG 15 mencakup perlindungan hutan, lahan basah, pegunungan, dan lahan kering, serta menghentikan kehilangan keanekaragaman hayati dan degradasi lahan.',
                'points'      => [
                    '15.1 Pada tahun 2020, menjamin pelestarian, restorasi, dan pemanfaatan berkelanjutan ekosistem darat dan perairan darat serta jasa ekosistemnya, khususnya hutan, lahan basah, pegunungan, dan lahan kering.',
                    '15.2 Pada tahun 2020, mendorong pelaksanaan pengelolaan semua jenis hutan secara berkelanjutan, menghentikan deforestasi, merestorasi hutan yang terdegradasi, serta meningkatkan penghijauan dan reforestasi secara substansial di tingkat global.',
                    '15.3 Pada tahun 2030, menanggulangi desertifikasi, merestorasi tanah dan lahan yang terdegradasi termasuk lahan yang terkena dampak desertifikasi, kekeringan, dan banjir, serta berupaya mencapai dunia yang bebas dari degradasi lahan.',
                    '15.4 Pada tahun 2030, menjamin pelestarian ekosistem pegunungan, termasuk keanekaragaman hayatinya, untuk meningkatkan kapasitasnya dalam memberikan manfaat yang esensial bagi pembangunan berkelanjutan.',
                    '15.5 Mengambil tindakan segera dan signifikan untuk mengurangi degradasi habitat alami, menghentikan hilangnya keanekaragaman hayati, serta pada tahun 2020 melindungi dan mencegah kepunahan spesies yang terancam.',
                    '15.6 Mendorong pembagian keuntungan yang adil dan merata dari pemanfaatan sumber daya genetik, serta mendorong akses yang tepat terhadap sumber daya tersebut.',
                    '15.7 Mengambil tindakan segera untuk mengakhiri perburuan dan perdagangan spesies flora dan fauna yang dilindungi serta mengatasi permintaan dan pasokan produk satwa liar ilegal.',
                    '15.8 Pada tahun 2020, memperkenalkan langkah-langkah untuk mencegah masuknya spesies asing invasif dan secara signifikan mengurangi dampaknya terhadap ekosistem darat dan air.',
                    '15.9 Pada tahun 2020, mengintegrasikan nilai-nilai ekosistem dan keanekaragaman hayati ke dalam perencanaan nasional dan lokal, proses pembangunan, strategi pengurangan kemiskinan, dan akuntansi.',
                    '15.a Memobilisasi dan secara signifikan meningkatkan sumber daya keuangan dari semua sumber untuk melestarikan dan memanfaatkan keanekaragaman hayati dan ekosistem secara berkelanjutan.',
                    '15.b Memobilisasi sumber daya yang signifikan dari semua sumber dan di semua tingkatan untuk membiayai pengelolaan hutan berkelanjutan serta memberikan insentif yang tepat kepada negara berkembang.',
                    '15.c Meningkatkan dukungan global bagi upaya memerangi perburuan dan perdagangan spesies yang dilindungi, termasuk dengan meningkatkan kapasitas masyarakat lokal untuk mengejar peluang mata pencaharian yang berkelanjutan.',
                ],
                'rce_action'  => 'RCE Jawa Timur berkolaborasi dalam program penghijauan lereng Gunung Bromo-Tengger-Semeru, restorasi lahan gambut, dan edukasi keanekaragaman hayati lokal.',
            ],
            [
                'number'      => 16,
                'title'       => 'Perdamaian, Keadilan dan Kelembagaan yang Tangguh',
                'description' => 'Menguatkan masyarakat yang inklusif dan damai untuk pembangunan berkelanjutan.',
                'targets'     => 12,
                'detail'      => 'SDG 16 bertujuan untuk mempromosikan masyarakat yang damai dan inklusif, menjamin akses keadilan bagi semua, serta membangun institusi yang efektif, akuntabel, dan inklusif.',
                'points'      => [
                    '16.1 Secara signifikan mengurangi semua bentuk kekerasan dan angka kematian terkait kekerasan di mana pun.',
                    '16.2 Mengakhiri pelecehan, eksploitasi, perdagangan, dan segala bentuk kekerasan dan penyiksaan terhadap anak.',
                    '16.3 Mendorong supremasi hukum di tingkat nasional dan internasional, serta menjamin akses yang sama terhadap keadilan bagi semua.',
                    '16.4 Pada tahun 2030, secara signifikan mengurangi aliran keuangan dan senjata gelap, memperkuat pemulihan dan pengembalian aset hasil kejahatan, serta memerangi segala bentuk kejahatan terorganisir.',
                    '16.5 Secara substansial mengurangi korupsi dan penyuapan dalam segala bentuknya.',
                    '16.6 Mengembangkan lembaga yang efektif, akuntabel, dan transparan di semua tingkatan.',
                    '16.7 Menjamin pengambilan keputusan yang responsif, inklusif, partisipatif, dan representatif di semua tingkatan.',
                    '16.8 Memperluas dan memperkuat partisipasi negara berkembang dalam lembaga tata kelola global.',
                    '16.9 Pada tahun 2030, memberikan identitas hukum bagi semua, termasuk pencatatan kelahiran.',
                    '16.10 Menjamin akses publik terhadap informasi dan melindungi kebebasan mendasar, sesuai dengan perundang-undangan nasional dan perjanjian internasional.',
                    '16.a Memperkuat lembaga nasional yang relevan, termasuk melalui kerja sama internasional, untuk membangun kapasitas di semua tingkatan, khususnya di negara berkembang, untuk mencegah kekerasan dan memerangi terorisme serta kejahatan.',
                    '16.b Mendorong dan menegakkan undang-undang dan kebijakan yang tidak diskriminatif untuk pembangunan berkelanjutan.',
                ],
                'rce_action'  => 'RCE Jawa Timur mendukung pendidikan perdamaian, resolusi konflik berbasis komunitas, dan penguatan tata kelola lokal melalui kemitraan dengan pemerintah daerah.',
            ],
            [
                'number'      => 17,
                'title'       => 'Kemitraan untuk Mencapai Tujuan',
                'description' => 'Menguatkan sarana pelaksanaan dan merevitalisasi kemitraan global untuk pembangunan berkelanjutan.',
                'targets'     => 19,
                'detail'      => 'SDG 17 adalah landasan dari seluruh agenda 2030. Tanpa kemitraan yang kuat antara pemerintah, sektor swasta, dan masyarakat sipil, 16 tujuan lainnya tidak akan bisa dicapai.',
                'points'      => [
                    '17.1 Memperkuat mobilisasi sumber daya domestik, termasuk melalui dukungan internasional kepada negara berkembang, untuk meningkatkan kapasitas pajak domestik dan penerimaan lainnya.',
                    '17.2 Negara maju melaksanakan sepenuhnya komitmen bantuan pembangunan resmi mereka, termasuk komitmen banyak negara maju untuk mencapai target 0,7% GNI untuk ODA.',
                    '17.3 Memobilisasi sumber daya keuangan tambahan untuk negara berkembang dari berbagai sumber.',
                    '17.4 Membantu negara berkembang dalam mencapai keberlanjutan utang jangka panjang melalui kebijakan terkoordinasi yang bertujuan mendorong pembiayaan utang, keringanan utang, dan restrukturisasi utang.',
                    '17.5 Mengadopsi dan melaksanakan rezim promosi investasi bagi negara kurang berkembang.',
                    '17.6 Meningkatkan kerja sama Utara-Selatan, Selatan-Selatan, dan kerja sama segitiga regional dan internasional, serta akses terhadap ilmu pengetahuan, teknologi, dan inovasi.',
                    '17.7 Mendorong pengembangan, transfer, diseminasi, dan penyebaran teknologi yang ramah lingkungan kepada negara berkembang dengan persyaratan yang menguntungkan.',
                    '17.8 Mengoperasionalkan bank teknologi dan mekanisme pengembangan kapasitas sains, teknologi, dan inovasi untuk negara kurang berkembang pada tahun 2017.',
                    '17.9 Meningkatkan dukungan internasional untuk melaksanakan pengembangan kapasitas yang efektif dan bertarget di negara berkembang guna mendukung rencana nasional pelaksanaan semua tujuan pembangunan berkelanjutan.',
                    '17.10 Mendorong sistem perdagangan multilateral yang universal, berdasarkan aturan, terbuka, non-diskriminatif, dan adil di bawah WTO.',
                    '17.11 Secara signifikan meningkatkan ekspor negara berkembang, khususnya dengan tujuan menggandakan pangsa ekspor global negara kurang berkembang pada tahun 2020.',
                    '17.12 Mewujudkan akses pasar bebas bea dan bebas kuota yang tepat waktu bagi semua negara kurang berkembang, sesuai keputusan WTO.',
                    '17.13 Meningkatkan stabilitas makroekonomi global, termasuk melalui koordinasi dan konsistensi kebijakan.',
                    '17.14 Meningkatkan koherensi kebijakan untuk pembangunan berkelanjutan.',
                    '17.15 Menghormati ruang kebijakan dan kepemimpinan setiap negara untuk menetapkan dan melaksanakan kebijakan pengentasan kemiskinan dan pembangunan berkelanjutan.',
                    '17.16 Meningkatkan kemitraan global untuk pembangunan berkelanjutan, dilengkapi dengan kemitraan multi-pemangku kepentingan yang memobilisasi dan berbagi pengetahuan, keahlian, teknologi, dan sumber daya keuangan.',
                    '17.17 Mendorong dan mendorong kemitraan publik, publik-swasta, dan masyarakat sipil yang efektif, berdasarkan pengalaman dan strategi sumber daya kemitraan.',
                    '17.18 Pada tahun 2020, meningkatkan dukungan pengembangan kapasitas kepada negara berkembang untuk meningkatkan ketersediaan data berkualitas tinggi, tepat waktu, dan dapat dipercaya.',
                    '17.19 Pada tahun 2030, mengandalkan inisiatif yang ada untuk mengembangkan pengukuran kemajuan pembangunan berkelanjutan yang melengkapi PDB.',
                ],
                'rce_action'  => 'Kemitraan adalah DNA RCE Jawa Timur. Kami menghubungkan universitas, pemerintah, LSM, komunitas, dan sektor swasta dalam jaringan aksi nyata untuk SDGs di Jawa Timur.',
            ],
        ];
    }

    public function index()
    {
        $sdgs = $this->getSdgs();
        return view('sdg.index', compact('sdgs'));
    }

    public function show(int $number)
    {
        $sdgs = $this->getSdgs();
        $sdg = collect($sdgs)->firstWhere('number', $number);

        if (!$sdg) {
            abort(404);
        }

        $prev = collect($sdgs)->firstWhere('number', $number - 1);
        $next = collect($sdgs)->firstWhere('number', $number + 1);

        return view('sdg.show', compact('sdg', 'prev', 'next', 'sdgs'));
    }
}
